# Generated by Django 6.0.1 on 2026-02-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='secret_scanning_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
