# Generated by Django 6.0.1 on 2026-01-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
