# Generated by Django 6.0.1 on 2026-01-20 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ci', '0001_initial'),
        ('commits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='commits.commit'),
        ),
    ]
