# Generated by Django 6.0.1 on 2026-01-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='snapshot_text',
        ),
        migrations.AddField(
            model_name='commit',
            name='parent_commit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='commits.commit'),
        ),
        migrations.AddField(
            model_name='commit',
            name='snapshot',
            field=models.JSONField(default=dict),
        ),
    ]
